### ISSUE TITLE
Features - Embed Images or other things?

### ISSUE THREAD

**Issue by mpixelz** [devdreamcatch/laravel-qrcode-campaign#10]
Hi,
your application looks great! but at the moment you only have web url embedding. Are you planning to add more options like vcard, wifi connection, social embedding or even images in the future?

**Comment by devdreamsolution** [comment]
> Hi,
> your application looks great! but at the moment you only have web url embedding. Are you planning to add more options like vcard, wifi connection, social embedding or even images in the future?

Hi, thanks for your interesting, yes, I will add more options, but the logo QR code is working now too.
