### ISSUE TITLE
Error Uploading logo

### ISSUE THREAD

**Issue by joseRamonLeon** [devdreamcatch/laravel-qrcode-campaign#11]
Hi friends!

First, congratulations for your project!. Yesterday one great friend asked me to make a qr to their bar/restaurant, and i am trying your application.

I have working wity only one error:

file_get_contents(https://terraza.qrbar.app/storage/logos/KnuyZ5BSJJtsJ6Ot9GhJZLrV9N47x60X1kvImgsO.png): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found 

I think it is a problem of permissions but i gave 777 to storage/logos and it is not working. Maybe i will need to clear cache after change permissions?

One question more! ;-)

What is the admin credentials access? Thanks a lot!

Best regards from Spain,

José Ramón León Somovilla

**Comment by FHARIS2019** [comment]
Wrote upload

**Comment by FHARIS2019** [comment]
Up

**Comment by devdreamsolution** [comment]
hi @joseRamonLeon 
did you set storage link in Laravel

**Comment by devdreamsolution** [comment]
I think this issue is resolved, so I close this.
